name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Validate Build
      with:
        cmake-version: '3.25.x'
      run: |
        cmake -S .
        make
        ./bin/AccountingTests
