name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Validate Build
      run: |
        set(cmake_version "3.25.0")
        cmake -S .
        make
        ./bin/AccountingTests
