name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Install Specific Version of CMake
      uses: ssrobins/install-cmake@v1
      with:
        version: 3.25.0

    - name: Validate Build
      run: |
        cmake --version
        cmake -S .
        make
        ./bin/AccountingTests
